server:
  port: 80

eureka:
  client:
    #true表示向注册中心注册
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
    #fetch-registry: true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要这个地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#设置feign客户端超时时间（Openfeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.example.springcloud.service.PaymentFeignService: debug
