server:
  port: 9004

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
         server-addr: 127.0.0.1:8848   #nacos地址
#        server-addr: 192.168.174.200:1111   #Nginx

management:
  endpoints:
    web:
      exposure:
        include: '*'