server:
  port: 8006

spring:
  application:
    name: cloud-payment-service

  cloud:
    consul:
      host: 192.168.174.200
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        #health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health