server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
        #自定义事务组名称 需要与seata-server中conf一致
        tx-service-group: qy_tx_group

  datasource:
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: 123456
      
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    io:
      seata: info

management:
  endpoints:
    web:
      exposure:
        include: '*'