server:
  port: 80

eureka:
  client:
    #true表示向注册中心注册
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
    #fetch-registry: true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要这个地址
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka

feign:
  hystrix:
    enabled: true
